### PR TITLE
fedops-build-report: Replaced graphite with mysql api

### PR DESCRIPTION
**Pull request by dmytro-danylov**

### CODE REVIEW

**Comment by roymiloh** [comment]
@dmytro-danylov @tompere Who's in charge of this PR?

**Comment by dmytro-danylov** [comment]
Tom asked for the feature, I implemented it. Both of us will be off until Sunday/Monday. So, we should wait till then, before merging.

**Comment by ronami** [comment]
@tompere @roymiloh @dmytro-danylov what's up with this PR? is it still relevant?

**Comment by ronami** [comment]
@tompere @dmytro-danylov Closing, please re-open if it's still relevant.

**Pull request closed without merging**
