### PR TITLE
use beforeLaunch and afterLaunce instead of onPrepare and onComplete

### PR DESCRIPTION
**Pull request by lbelinsk**
Related to issue #87

### CODE REVIEW

**Comment by ronami** [comment]
Isn't it a breaking change?

**Comment by roymiloh** [comment]
No. CDN server is planned to put up once per all instances. `onPrepare` invoked per instance (hence we cannot sharding, so it's one step towards).

**Comment by ronami** [comment]
@lbelinsk any updates on this?

**Comment by roymiloh** [comment]
@tqmukas We still merge users' `onPrepare` (or any other property), we've just moved the snippet that opens and closes the so-called cdn server to be in `onLaunch` instead of `onPrepare`.

**Pull request merged**
