### PR TITLE
haste-preset-yoshi: make statics dev cdn listen not only on loopback, but on all network interfaces

### PR DESCRIPTION
**Pull request by jakutis**
by the way, default haste server artifacts listen on all hosts, i.e. default is not 127.0.0.1, but 0.0.0.0

### CODE REVIEW

**Comment by ranyitz** [comment]
@jakutis Do you still need this feature?

**Comment by shahata** [comment]
it is still needed. currently you can only connect to development server on local machine. this is required for cases where you want, for example, to connect to development server from your mobile device.

**Comment by ranyitz** [comment]
Continue on #285

**Comment by jakutis** [comment]
@ranyitz why a different PR with same diff?

I still need this and I would have loved to have contributed to Yoshi...

**Comment by ranyitz** [comment]
@jakutis, The diff on this PR was very complex to merge (we moved a lot of directories over the last few months) ,I've closed #285, Feel free to open a new one.

**Comment by ranyitz** [comment]
@jakutis Can you open a PR? @vshuhaiev would like this feature to land in the next version.

**Comment by jakutis** [comment]
@ranyitz okey, will do it this week

**Comment by ranyitz** [comment]
Hey @jakutis, I'm sorry, but Also @amimagid requested this feature and we can't wait anymore, this feature merged on #319 and will be in version `v2.7.0`.

There is a lot to do in yoshi, we are looking forward more contributions from you! 🥇

**Pull request closed without merging**
