### PR TITLE
feat (cdn) - support ssl

### PR DESCRIPTION
**Pull request by talbenmoshe**
add "ssl": true under "yoshi.servers.cdn" to enable serving cdn files over ssl.

### CODE REVIEW

**Comment by viliusl** [comment]
@talbenmoshe - why not actually use self-signed certificates?

like: https://github.com/wix-platform/wix-node-platform/blob/master/testing/wix-http-testkit/index.js#L54 ?

**Comment by talbenmoshe** [comment]
@viliusl , I did create a self-signed cert using openssl. But using 'pem' may be better in local test mode.. The only disadvantage I can think of, is the time needed to create a cert on each run. I will test it, if it's a non-issue, I will change to 'pem'.

WDYT?

Thanks!

**Comment by viliusl** [comment]
@talbenmoshe - cannot elaborate on timing, but you are right, we should pay attention to it. I like autogenerated certs as then I don't need to worry about maintenance, expiration, etc.

Imho both solutions are valid, just wanted to share how I solved it already in another place:)

**Comment by talbenmoshe** [comment]
@viliusl, So its about 10.099ms to create the server using pre-created certs and about 4968.180ms via 'pem' module.
I don't know if its a big issue since it only happens once, but if people stop and start their servers often then it might be an issue for them.
Also, when using pem, its pretty much guaranteed to work well everywhere.. while I don't know if they way I created the certs will work on other machines..

I guess Infra guys should decide, No problem doing it either way..

**Comment by talbenmoshe** [comment]
Branch corrupted see: https://github.com/wix/yoshi/pull/291

**Pull request closed without merging**
