### PR TITLE
jsdom cleanup

### PR DESCRIPTION
**Pull request by yanivefraim**

### CODE REVIEW

**Comment by yanivefraim** [comment]
After a short discussion we decided that this solution is not good enough.

Current solution will be:
1. `require('jsdom-global')(..., { url: 'http://some-url.com' });` in mocha setup
2. in IT tests choose axios adapter explicit to be httpadapter.
3. remove all jsdom stuff from tests.

See https://github.com/node-nock/nock/issues/699#issuecomment-298105814 for more details

I'll fix PR accordingly

**Comment by yanivefraim** [comment]
So current solution:
`mocha-setup.js` will have:

```
//...
require('jsdom-global')(undefined, {url: getTestBaseUrl()});
const axios = require('axios');
//...
``` 

And then inside IT tests we can have:

```
const axiosInstance = axios.create({
  baseURL: getTestBaseUrl(),
  adapter: require('axios/lib/adapters/http')
});

axiosInstance.get(...
```

@ronami - WDYT?

**Comment by ronami** [comment]
This PR and this (https://github.com/wix/yoshi/pull/85/files) PR are essentially the same PR(?).
Bottom line, I agree with Yaniv, I think we should run component tests with jsdom running under a URL and have axios use JSDOM's APIs (https://github.com/node-nock/nock/issues/699#issuecomment-298105814).

As for IT tests, we should probably run them as a separate mocha process, or in the meantime, force the http adapter.

**Comment by yanivefraim** [comment]
@ronami - 
> This PR and this (wix-private/wix-js-stack#506) PR are essentially the same PR(?).

yes, this is the same PR (here for open source project and on private generator as well)

**Comment by ronami** [comment]
@yanivefraim is this still relevant? can we close?

**Comment by yanivefraim** [comment]
We will have a new PR with correct jsdom handling

**Pull request closed without merging**
