### PR TITLE
added jest preset types pointer

### PR DESCRIPTION
**Pull request by amiryonatan**
### 🔦 Summary
Set the types property to point to your declaration file

### CODE REVIEW

**Comment by ronami** [comment]
Thanks for the PR 🙏 

I'm not sure if this is necessary: The `types` prop is only used when a package is imported and you never directly import `jest-yoshi-preset`. We could try to have the types go into `node_modules/@types/...` so they are included automatically.

Does this solve a problem you encountered?

**Comment by amiryonatan** [comment]
@ronami yeah:
right now I'm importing the types like that:
/// <reference types="../../../node_modules/jest-yoshi-preset/types" />

I don't want to expose page as a global, since we have tests that run either in sled / local e2e.
I have a class that supplies the relevant page object depending on the environment It's running

**Comment by amiryonatan** [comment]
I would like to do:
/// <reference types="jest-yoshi-preset" /> which is cleaner and nicer :)

**Comment by amiryonatan** [comment]
@ronami ?

**Pull request merged**
