### PR TITLE
Unpin typescript in templates

### PR DESCRIPTION
**Pull request by amitdahan**
### 🔦 Summary
It was locked to `~3.6.0` for some reason. 

UPDATE: 
Seems to pass ✅!

### CODE REVIEW

**Comment by amitdahan** [comment]
@yanivefraim I'll attempt to unpin the rest :)

**Comment by ranyitz** [comment]
TypeScript breaks on minor versions - https://github.com/microsoft/TypeScript/issues/14116#issuecomment-280410804

**Comment by amitdahan** [comment]
@ranyitz pinned `~3.9.0` 👍

**Comment by amitdahan** [comment]
Will merge when green

**Pull request merged**
