### PR TITLE
Generate git repo when requested

### LINKED ISSUE #521: Git hooks don't work until husky is reinstalled
# 🐛 Bug Report

### 😯 Current Behavior

When generating a new project git hooks don't work until husky is reinstalled.

### 🤔 Expected Behavior

Git hooks should work right after generating a new project.

### 💁 Possible Solution 

Husky cannot install the git hooks when it gets installed because there isn't a git repository initialised yet. If the generated project should be a git repository, we should also `git init` before running `npm install` (Notice the _if_, since there are other issues about creating a project inside a monorepo which do not need a git repo or husky, maybe we should also ask the user if he wants to create a git repo).

### 🌍 Your Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    npm: 6.4.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    yoshi: ^3.0.0 => 3.6.0

 Yoshi config
{
  "entry": {
    "test-bmm-module": "./module",
    "test-bmm-app": "./client"
  },
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "react-addons-css-transition-group": "React.addons.CSSTransitionGroup",
    "lodash": "_",
    "urijs": "URI",
    "@wix/business-manager-api": "BusinessManagerAPI",
    "react-module-container": "reactModuleContainer"
  }
}
```

### PR DESCRIPTION
**Pull request by netanelgilad**
### 🔦 Summary
Fixes #521. In this PR, we `git init` a new generated project if the user answered yes to the question `Is this a git repository?`. I've added the question to support generating a project without a git repository as a very early support for generating a project inside a monorepo. Adding the question relates to issues like #456, allowing us to also not generate certain parts if we don't need a git repo (like not installing husky).

### 🗺️ Test Plan
Added e2e tests to make sure a git repo has been initialised if requested.

### CODE REVIEW

**Comment by ranyitz** [comment]
Nice work!

We know that a generated project without a git repo causes some bugs and I think we should try to avoid it if possible. Maybe we can detect whether we are already in a git repo, and create one only if needed.

@netanelgilad what do you say?

**Comment by netanelgilad** [comment]
@ranyitz I've made the changes we talked about. check it out.

**Comment by ranyitz** [comment]
@netanelgilad Looks good, let's move the e2e tests into `jest` and merge.

**Comment by netanelgilad** [comment]
@ranyitz Ready for review on my end.

**Pull request merged**
