### PR TITLE
Update jest transform

### PR DESCRIPTION
**Pull request by yanivefraim**
In TS projects we want TS to transpile both TS and JS files.

### CODE REVIEW

**Comment by ronami** [comment]
I think we can add a test for that pretty easily with the new integration tests. Wdyt?

**Comment by yanivefraim** [comment]
> I think we can add a test for that pretty easily with the new integration tests. It should test the use-case of having a JavaScript file in a TypeScript project that will need transpilation. Wdyt?

cool. I would add another test for (already merged) `regenerator-runtime`

**Comment by ronami** [comment]
Just realized, we do the same mistake when we bundle with Webpack: `.js` files go through `babel-loader` and `.tsx?` file go through ts-loader.

**Comment by ronami** [comment]
Closing for now. This will be a breaking change that we plan on including in the next version.

**Pull request closed without merging**
