### PR TITLE
Fix hmr for css/scss/less files

### LINKED ISSUE #262: HMR "auto" not reloading for CSS changes
# 🐛 Bug Report

### 😯 Current Behavior

I'm working with a newly generated project with Yoshi `HMR` flag set to `auto`. I modify a scss file in dev mode (`npm start`) and save the file. The actual behavior: nothing reloads.

### 🤔 Expected Behavior

HMR should kick in and reload the view

### 🌍 Your Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.7.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 5.8.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 66.0.3359.139
    Firefox: 57.0.4
    Safari: 11.1
  npmPackages:
    yoshi: ^2.1.2 => 2.1.7

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

### PR DESCRIPTION
**Pull request by yavorsky**
### 🔦 Summary
This PR fixes #262 
According to this issue [ExtractTextPlugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/384) isn't support hmr.
Actually we have 2 solutions:
1. Replace ExtractTextPlugin with MiniCssExtractPlugin and add css-hot-loader. But there are [so much changes](https://github.com/shepherdwind/css-hot-loader#webpack-4) for us and it's not so good as a hotfix solution.
2. Don't use it for a cdn task by explicitly providing `separateCSS: false`. It should be safe since we don't need this option for webpack dev server at all. We are not working with build ouput, just with abstract bundle hidden under the dev-server's hood.

So this PR provides the 2-nd solution.

### CODE REVIEW

**Comment by yavorsky** [comment]
@ranyitz I thought it's just for webpack-dev-server, which doesn't create files inside `dist`/`src`, etc, so actually `separateCss` will be present for `transpileJavascript` and other stuff, but won't for dev server.

Sure, `css-hot-loader` is a good long-term solution. But does `separateCss: false` will somehow affect users if we are using it just for dev-server?

**Comment by ranyitz** [comment]
@yavorsky That looks great! ❤️  I'll create a branch for *yoshi@3* and we'll merge the PR to there.

**Comment by yavorsky** [comment]
Awesome 👨‍🚀

**Comment by ranyitz** [comment]
moved to #281 and merged to version 3 branch

**Pull request closed without merging**
