### PR TITLE
upgrade webpack to version 3.8.1

### PR DESCRIPTION
**Pull request by sdoomz**
https://github.com/wix/yoshi/issues/357

@roymiloh @ipanasenko should we also update some other modules?

### CODE REVIEW

**Comment by ipanasenko** [comment]
I'd like to use latest versions of everything, of course ☺️

**Comment by roymiloh** [comment]
Thanks.

Just for the record - I think it's ok to move from `~` to `^` here. Webpack respects semver, so no breaking changes should be introduced as minor ones.

**Comment by ipanasenko** [comment]
@roymiloh only npm modules I know that don't respect semver are Wix's own :)
IMO, it's pretty safe to use `^` in every dependency

**Comment by sdoomz** [comment]
@ipanasenko In the other hand, it's strange to change this rule for webpack module only. If we want to replace  `~` with `^` we should do it for dependencies, shouldn't we? 

So, maybe better to ask @viliusl what was a motivation for [this commit](https://github.com/wix/yoshi/commit/505763390c6607c8f5cb576ccbedac90c737c265)

**Comment by ipanasenko** [comment]
@sdoomz I'm all for that. Probably you wanted to ask @roymiloh ?

**Comment by roymiloh** [comment]
It's the current decision we made as a team. It's a tradeoff between safely and flexibility/quicker updates. In the case of Webpack (and maybe even with other deps - we can reconsider it) I think it's ok to change to caret.

@ipanasenko Just for the record - angular@1 has not respected semver and TypeScript applies breaking changes on minor as well, so it's definitely not only @ Wix:)

**Pull request merged**
