### PR TITLE
remove webpack lock from yoshi

### PR DESCRIPTION
**Pull request by matveyok**
### 🔦 Summary
Remove lock from webpack version due to this issue that was solved:
https://github.com/webpack/webpack/issues/8656

### CODE REVIEW

**Comment by matveyok** [comment]
I hope it will fix our problem and we will be able to migrate to yoshi 4.x.x :)

**Comment by matveyok** [comment]
About the failing tests, the bundle is a bit different but still have what the tests wants:
image

What do you think, is it ok and change the test to have `\\` ?

@ranyitz

**Comment by ranyitz** [comment]
@matveyok Yes! Nice digging into that.

Those tests are **not good** because they are too aware of the implementation.
In the future, we'll ditch them in favor of the kitchen sink tests.

________________________________

For now, just adjust the test, let's make it pass and I'll merge it :)

Again, sorry for the hassle, and thanks for the effort! 👍

**Comment by matveyok** [comment]
@ranyitz I don't understand the lint build and how it passed before, I agree with the error... there is multiple tests with the same title 🤷‍♂️

**Pull request merged**
