### PR TITLE
add raw css loader

### LINKED ISSUE #34: Ability to include raw css files
I have a project, which uses css modules. It has a dependency on "component" module, which internally also uses css modules, but provides transpiled and pre-built js + css. The outcome is
component.css that contains classnames, matching component.js (css modules applied).
 
Importing component.js and component.css in my main project causes yoshi to apply css modules again for component.css, resulting in a mismatch with class names, used in component.js. 

`
:global {
@import "component/component.css"
}
` 

doesn't work, it still applies css modules for the component.css.

What the end result could be - ability to import "raw" css files that would be included in the bundle as is - maybe a different loader for webpack would do the trick.

### PR DESCRIPTION
**Pull request by donatas**
fixes #34 . 
agreed with @tqmukas that he'll investigate a more generic approach to include unmodified/unprocessed CSS files to a project, but it will be a separate effort

### CODE REVIEW

**Comment by tqmukas** [comment]
The new raw loader is missing in webpack configuration for specs.
https://github.com/wix/yoshi/blob/master/yoshi/config/webpack.config.specs.js#L22-L23

**Comment by ronami** [comment]
@donatas @tqmukas is this still relevant? what's the status?

**Comment by donatas** [comment]
@ronami Less relevant. Talked with @tqmukas about a more generic approach for third party css, I think this PR can be closed as it's outdated

**Comment by ronami** [comment]
@donatas closing, please re-open if it's relevant again.

**Pull request closed without merging**
