### PR TITLE
WIP - Migrate to node 10

### PR DESCRIPTION
**Pull request by yairhaimo**
### 🔦 Summary
Migrate to node 10 LTS

### CODE REVIEW

**Comment by yairhaimo** [comment]
Which PR label fits?

**Comment by ranyitz** [comment]
After merging the Typescript tests PR, also change here - https://github.com/wix/yoshi/pull/933/files#diff-f3c553c8d396ec9a27616062dd09eb95

**Comment by ronami** [comment]
Most of these changes were introduced already (final ones in #1008). I think the only exception is that we're still not forcing a minimum node version of 10.

**Comment by ronami** [comment]
Closing. Please re-open if it's still relevant.

**Pull request closed without merging**
