### PR TITLE
merge all created style tags into one

### PR DESCRIPTION
**Pull request by eranshabi**
so we won't have so many style tags in the html

### CODE REVIEW

**Comment by shahata** [comment]
@roymiloh is it good to merge? what are the advantages of having this option?

**Comment by roymiloh** [comment]
Essentially, it doesn't create `<style>` per module, which is much cleaner imo. @eranshabi also claims that it helps while developing, not sure how tho.

I'm not merging because I'd like to think more about the implications and [see how the source maps (don't?) work](https://github.com/webpack-contrib/style-loader/issues/134).

**Comment by roymiloh** [comment]
Well, we came into conclusion that source maps don't work with inline styles anyway, so everything is ok.

**Comment by roymiloh** [comment]
Thanks.

**Pull request merged**
