### PR TITLE
added resolve symlinks flag

### PR DESCRIPTION
**Pull request by amiryonatan**
### 🔦 Summary
Added the option to use webpack resolve symlinks as exists in Yoshi@4

### CODE REVIEW

**Comment by ronami** [comment]
Thanks for the PR @amiryonatan 🙏

Can you please explain what's the use-case for resolving symlinks?

**Comment by amiryonatan** [comment]
@ronami 
In the ADI monorepo we have these dependencies:

A --> C
A --> B --> C

We use lerna to manage the dependencies, and therefor, all the project are linked.
A is our application, when we start / build it locally we get module C bundled twice inside, because webpack doesn't resolve the linked directories to the source directory.
When turning the flag on, the issue is fixed.

**Comment by ranyitz** [comment]
We don't create new features for Yoshi@3 so I rather present it as an undocumented environment parameter.

Also, the `experimental` prefix is saved for testing new experimental features, which is not the case.

I suggest something like:

```js
WEBPACK_RESOLVE_SYMLINKS=true
```

Which will default to `false`, no need for documentation or tests in my opinion.

What do you think @ronami?

**Comment by amiryonatan** [comment]
@ranyitz better ?

**Pull request merged**
