### PR TITLE
Upgrade eslint to v4

### PR DESCRIPTION
**Pull request by astrauka**
Upgrade eslint to v4

yoshi uses 3.19.0 eslint version, prettier uses eslint version 4.5.0.
The `indent` rule behaves differently https://eslint.org/docs/user-guide/migrating-to-4.0.0#indent-rewrite.

```javascript
    {isCustomFeedWidgetEnabled ? (
      [
        <AddOnCustomFeedWidget key="custom-feed-widget"/>,
        <HorizontalSeparator key="separator" className={styles.separator}/>,
      ]
    ) : null}
```
is valid for eslint v4 but invalid for eslint v3.

I want to use prettier and thus need to upgrade yoshi eslint version.

### CODE REVIEW

**Comment by viliusl** [comment]
@ronami - could you give your feedback on this one?

**Comment by ronami** [comment]
Looks good, how do we plan not to break other projects? We're not only bumping yoshi's linting, but also the `eslint` version used to lint `yoshi`'s end users.

**Comment by astrauka** [comment]
Some options:
* configure https://github.com/wix/eslint-config-wix rules to avoid breaking other projects. We might still break those as we will not test all possible [rule * code variation] scenarios
* provide information about the breaking change and ask to run `eslint --fix`
  * add info to README
  * add post install message

@ronami what do you think, maybe there are better ways?

**Comment by ronami** [comment]
I want to merge this PR and provide information about the breaking changes. I don't think that making this work as a feature flag will be a good idea. I want to wait until `ci-police` is ready and merge it as a major version. cc @shahata

**Pull request closed without merging**
