### PR TITLE
Add fedops build report plugin to build

### PR DESCRIPTION
**Pull request by yakirn**
1. Follow up to https://github.com/wix/yoshi/pull/126

2. Allow fedops logger to report the version number by defining a new webpack plugin (replace window.__CI_APP_VERSION__ with the artifact version number from CI)

### CODE REVIEW

**Comment by yakirn** [comment]
added tests.
@roymiloh testing of integration with yoshi-fedops-build-report is limited only console output as there is no actual change to files

**Comment by jonathanadler** [comment]
@ronami @roymiloh 
We're kind of stuck here. We don't understand why the checks fail.
Do you have some insights for us maybe?
By the way, locally we have many test fails, but not on things we changed.

**Comment by jonathanadler** [comment]
@roymiloh @ronami 
How about we merge this PR, and we can work on adding a testkit afterwards?
I'm already working on the pr.

**Comment by jonathanadler** [comment]
@roymiloh 
pinging

**Pull request merged**
