### PR TITLE
chore(lint): upgrade prettier to v2

### PR DESCRIPTION
**Pull request by liorcode**
# 🔦 Summary
Upgrade prettier 1.x to 2 
See #2515 

Note that since prettier 2 introduced some breaking changes, this PR also effects the yoshi monorepo itself.
To align all the yoshi projects with the new version, `yarn lint --fix` should run on the entire repo.
As this would reduce in a large PR, I didn't want to do it here.

### CODE REVIEW

**Comment by liorcode** [comment]
done 👍

**Comment by ranyitz** [comment]
@liorcode The templates tests are flaky and not a result of this PR.
The unit tests are failing for a reason. (We test our eslint config and it fails because of prettier instead of the real reason)

I don't want to waste your time, so let me know if you can take this. In case your stuck I can make a PR to this PR.

Thanks

**Comment by liorcode** [comment]
it appears the tests are failing because the tests needs to be updated to match the new prettier rules.
I'd be happy if you could PR the PR :)

**Comment by ranyitz** [comment]
@liorcode here is the PR https://github.com/liorcode/yoshi/pull/1

**Pull request merged**
