### PR TITLE
monorepoflow – remove stripOrganization from the error logs

### PR DESCRIPTION
**Pull request by tuchk4**
Current error message is:

image

Could not find an app with the name of `editor-elements-library` but it exists at the `Apps found:`

Error message with this PR is:

image

### CODE REVIEW

**Comment by tuchk4** [comment]
Also the related issue:
to run package build we use `yoshi build package-name` (dir name)
to run package start we use `yoshi build @wix/package-name`  (pkg name)

let's choice the one style and I will update the PR.

**Comment by tuchk4** [comment]
Updated:

now start and build commands do the same pkg filter.

image

**Comment by yavorsky** [comment]
I would also make `Could not find`... red. It's not really obvious this message is explaining an error.

**Comment by ronami** [comment]
This PR ended up being a breaking change for local development. Existing scripts need to be changed from `yoshi start @wix/app` into `yoshi start app`.

**Pull request merged**
