### PR TITLE
create-yoshi-app | feat (i18next with ICU format): i18next & ICU integration.

### PR DESCRIPTION
**Pull request by etaybarzilay89**
Using ICU format in i18next.

- adding i18next-icu to package.json of client/fullstack templates (both js and ts).
- enriching i18next with i18next-icu plugin.

### CODE REVIEW

**Comment by itaibenda** [comment]
This adds around *5.4kb gzip* to the bundle including `intl-messageformat` which is *4.79kb gzip*

**Comment by yairhaimo** [comment]
Thanks for the contribution!

Two notes:
- Can you please explain what this PR does? What is the effect on the users? Why do we need it?
- This PR updates only some of the templates (missing bizmgr, ooi)

**Comment by etaybarzilay89** [comment]
Yes of course:
- This PR adds an i18next-ICU plugin to i18next (our translation tool), which lets us use ICU syntax in our translations json (https://formatjs.io/guides/message-syntax/).
It means that whenever we use the "t" function, it evaluates the translation value in an "ICU way", similar to what happens today when we want to inject arguments to the translation value but with more powerful abilities.

It will help us solve existing translations problems (such as pluralization, gender, dates and so on).
You can read about it here (documentation is another PR we have):
https://github.com/wix-private/fed-handbook/pull/224

or play with it here:
https://github.com/wix-private/translations_icu_example_project

(It should also be on production, but CI has a bug so it's not yet there):
https://apps.wix.com/translations-icu-examples-project
.

- This PR should not effect our users without them using the new abilities of ICU syntax explicitly, this is because ICU is a super set of i18next syntax.
More over, because it only applies to new projects made by yoshi with i18next, there is no risk of not integrating correctly with not-yoshi or not-i18next projects.


- This PR updates only fullstack and client templates since in other templates the i18next version does not yet support ICU format. 
We saw that there is a PR to bump up i18next version on other templates as well. once they'll merged, it will be possible to apply the plugin on them as well.

**Comment by yairhaimo** [comment]
Thank you.
Can you point me to the PR that bumps i18next in the other templates?
I rather that we first bump the versions across all templates and then update this PR to match, instead of doing it gradually.

**Comment by itaibenda** [comment]
@yairhaimo https://github.com/wix/yoshi/pull/1344

**Comment by yairhaimo** [comment]
That PR only bumps in the client and fullstack templates

**Comment by itaibenda** [comment]
Because the other templates are using i18next version which isn't supported with ICU
The remaining templates could be updated if the following PR will bump their versions: https://github.com/wix/yoshi/pull/1344

**Comment by itaibenda** [comment]
better solved here: https://github.com/wix/yoshi/pull/1407

**Pull request closed without merging**
