### PR TITLE
Add jest-watch-typeahead plugins

### PR DESCRIPTION
**Pull request by yakirn**
### 🔦 Summary
This PR adds [typeahead plugins](https://github.com/jest-community/jest-watch-typeahead) to jest watch mode
It will help developers when filtering tests by autocomplete files/tests names as they type:

demo

### 🗺️ Test Plan
As far as I can see there is no need in automated tests for this change.

*Update*
I added the `watchPlugins` in the wrong location, now fixed and tested locally.

### CODE REVIEW

**Comment by Schniz** [comment]
Hey @yakirn! I'm sorry for not being responsive.

We are currently working on some other things and we'll get back to Yoshi as soon as possible!

The tests actually pass here, have you installed all the dependencies on the `yoshi` clone? have you installed them on your test project?

btw, I have added the gif from the repo to the description too, to give more context 😸

**Comment by shlomitc** [comment]
I think it's a good addition and very much needed in our projects.

Although it can easily be added to every project manually, I do think that when migrating from yoshi 2.x to 3.x, people will be surprised to see it is missing.

**Comment by yakirn** [comment]
@ronami Updated to version 4.x can we merge this please? :)

**Comment by yairhaimo** [comment]
Merged in #1150

**Pull request closed without merging**
